
const CONSTANTS = {

    //USER EVENTS
    RESET_USER_PASSWORD: "RESET_USER_PASSWORD",
    CREATE_USER: "CREATE_USER",
    DEACTIVATE_USER: "DEACTIVATE_USER",
    UPDATE_USER: "UPDATE_USER",

    //TEAM
    CREATE_TEAM: "CREATE_TEAM",
    TEAM_SETTING: "TEAM_SETTING",

    //ROLE
    CREATE_ROLE: "CREATE_ROLE",

    //MISC
    API_URL: "http://localhost:3001/api/",
    TOKEN_NAME: 'token'
}

export default CONSTANTS